# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/roquie/multisite/models/setting/fields.yaml

# Model Class name
modelClass: Roquie\Multisite\Models\Setting

# Default redirect location
defaultRedirect: roquie/multisite/settings

# Create page
create:
    title: roquie.multisite::lang.controller.create
    redirect: roquie/multisite/settings/update/:id
    redirectClose: roquie/multisite/settings

# Update page
update:
    title: roquie.multisite::lang.controller.create
    redirect: roquie/multisite/settings
    redirectClose: roquie/multisite/settings
